TEST_PLAYLIST_ID = '38Iy3a78T4ycd6k3UDLbyr'
TEST_2_PLAYLIST_ID = '6j1VdtBOquLnmymBZCYtvz'

MY_SONGS_PLAYLIST_ID = '7GJaWvnybhnTFblm1GURQI'
GOOD_PLAYLIST_ID = '2YoTDtNqEagbeStoy7wGeC'
BEST_PLAYLIST_ID = '0YEu9RLpd9evCc8S1BrplH'
