MY_SONGS_PLAYLIST_ID = '7GJaWvnybhnTFblm1GURQI'
GOOD_PLAYLIST_ID = '2YoTDtNqEagbeStoy7wGeC'
BEST_PLAYLIST_ID = '0YEu9RLpd9evCc8S1BrplH'

MIN_DISTANCE_TWO_CLONES_AS_FRACTION = 1 / 3
MIN_DISTANCE_THREE_CLONES_AS_FRACTION = 1 / 4
