USER_ID = '11170957184'
# Low and high in order to choose a random minimal
# distance between the two values for every track
LOW_MIN_DISTANCE_TWO_CLONES_AS_FRACTION = 1 / 4
HIGH_MIN_DISTANCE_TWO_CLONES_AS_FRACTION = 1 / 3

LOW_MIN_DISTANCE_THREE_CLONES_AS_FRACTION = 1 / 5
HIGH_MIN_DISTANCE_THREE_CLONES_AS_FRACTION = 1 / 4
